kumuluzee:
  name: scrum-service
  version: 1.0.1-SNAPSHOT
  env:
    prod: false
    name: dev
  dev:
    scan-libraries:
      - rest-utils
      - lib
  server:
    show-server-info: false
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count"
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi/specs
    ui:
      enabled: true
      mapping: /openapi/ui
      server-auto-config:
        enabled: false
  logs:
    loggers:
      - name: ''
        level: INFO
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/mainDB
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:postgresql://localhost:5432/scrum-db
      username: postgres
      password: postgres
      pool:
        max-size: 20
  database-schema-migrations:
    enabled: true
    liquibase:
      changelogs:
        - jndi-name: jdbc/mainDB
          file: db/migrations/db.master.xml
          startup:
            update: true
notifications:
  email:
    host: smtp.host.com
    port: 465
    display-name: SMRPO
    username: user@host.com
    password: userpassword
web-ui:
  allowed-origins: http://localhost:4200, https://scrum-web.netlify.app
  oidc-callback: /callback/oidc
templates:
  cache-enabled: false
users:
  password:
    min-length: 12
    max-length: 128